Parameterize probe values for Jaeger-chart
aws/eks-charts pull request #391
Opened 2020-12-14 09:44 UTC by olovholm

Issue #, if available: 390

Description of changes:
* Parameterize liveness and readiness probes
* Sets default values in Chart to Kubernetes default values

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-12-14 15:54 UTC, fawadkhaliq requested changes
@olovholm thanks for the pull request. Looks good overall. Added a couple of comments

2020-12-14 15:54 UTC, fawadkhaliq commented on stable/appmesh-jaeger/values.yaml
> +    failureThreshold: 3
Can you please also update the README configuration section [1] with new the params

[1] https://github.com/aws/eks-charts/blob/master/stable/appmesh-jaeger/README.md#configuration

2020-12-14 15:54 UTC, fawadkhaliq commented on stable/appmesh-jaeger/values.yaml
> +  ## Prometheus server readiness and liveness probe initial delay and timeout
typo: Prometheus?

2020-12-17 15:34 UTC, fawadkhaliq approved these changes
lgtm

2020-12-17 15:34 UTC, merged

2020-12-21 15:11 UTC, olovholm commented
@fawadkhaliq : Thanks for review. Branch now merged, but could we have a release? From the build jobs it doesn't look like the helm charts are deployed, and I cannot find the new version in the chart-repository.