Update Envoy sidecar resources request
aws/eks-charts pull request #864
Opened 2022-12-20 11:52 UTC by yws-ss

### Issue

Per [AWS document](https://docs.aws.amazon.com/app-mesh/latest/userguide/envoy.html) mentioned, AWS App Mesh recommend allocating **512** CPU units and at least **64 MiB** of memory to the Envoy container. On Fargate the lowest amount of memory that you can set is **1024 MiB** of memory.

### Description of changes

Change the helm default resource's value to match recommendation. However, user still need to manually change if deploy it on Fargate.

### Checklist
- [V] Added/modified documentation as required (such as the `README.md` for modified charts)
- [V] Incremented the chart `version` in `Chart.yaml` for the modified chart(s)
- [V] Manually tested. Describe what testing was done in the testing section below
- [V ] Make sure the title of the PR is a good description that can go into the release notes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-01-10 00:05 UTC, bendu commented
Hi @yws-ss 

Thanks for your PR! The app mesh controller charts are actually mastered in the [controller repo](https://github.com/aws/aws-app-mesh-controller-for-k8s/tree/master/config/helm/appmesh-controller) and sync'd over. Please check that repo to make any PR updates

2023-01-10 00:09 UTC, bendu requested changes

2023-01-10 00:09 UTC, bendu commented on stable/appmesh-controller/README.md
> +`sidecar.resources.requests` | Envoy container resource requests | `requests: cpu 512 memory 64Mi`
So this is where ECS and Kubernetes differ. ECS equates 1024 CPU units to 1 AWS vCPU, whereas Kubernetes uses 1 cpu as 1 vCPU.

More about CPU units for k8s in the [docs](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#cpu-units).

2023-01-10 00:09 UTC, bendu commented on stable/appmesh-controller/README.md
> +`sidecar.resources.requests` | Envoy container resource requests | `requests: cpu 512 memory 64Mi`
This needs to be changed to something like `500m` or `0.5`

2023-01-10 00:09 UTC, bendu commented on stable/appmesh-controller/values.yaml
> +      cpu: 512
Same as above

2024-09-24 14:29 UTC, bryantbiggs commented
please see the chart README notice

> ⚠️ This controller is published in multiple repos: Contributions to this Helm chart must be written to [aws/aws-app-mesh-controller-for-k8s Github repo.](https://github.com/aws/aws-app-mesh-controller-for-k8s/tree/master/config/helm/appmesh-controller) PRs to other repos like aws/eks-charts may be closed or overwritten upon next controller release.

closing this here but please feel free to open on the repo where the chart source is located

2024-09-24 14:29 UTC, closed without merging