add ability to turn PodSecurityPolicy on or off in aws-for-fluent-bit
aws/eks-charts pull request #888
Opened 2023-01-18 15:22 UTC by razorsk8jz

### Issue

In kubernetes 1.25 pod security policies were deprecated - see issue https://github.com/aws/eks-charts/issues/856 and https://github.com/aws/eks-charts/issues/810

### Description of changes

Adding the ability to turn off the pod security policy will allow people to use the chart if they are on kubernetes 1.25+

### Checklist
- [x] Added/modified documentation as required (such as the `README.md` for modified charts)
- [x] Incremented the chart `version` in `Chart.yaml` for the modified chart(s)
- [x] Manually tested. Describe what testing was done in the testing section below
- [x] Make sure the title of the PR is a good description that can go into the release notes

### Testing

I was able to deploy the chart by setting rbac.pspEnabled=false

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-01-19 22:09 UTC, PettitWesley requested changes

2023-01-19 22:09 UTC, PettitWesley commented on stable/aws-for-fluent-bit/templates/psp.yaml
> +{{- if .Values.rbac.pspEnabled }}
@razorsk8jz are you sure that you want to wrap this entire file with this option? I think that means this existing file will not get generated unless you have this new default false field enabled. That seems non-desirable. 

Can you please explain the intention behind this? Should the option be default true?

I also see here that pod security policy is removed in newer k8s version: https://kubernetes.io/docs/concepts/security/pod-security-policy/

So I'm not sure it makes sense to move forward with this.

2023-01-24 17:30 UTC, razorsk8jz commented
This also aligns with the request in https://github.com/aws/eks-charts/issues/810 to default to false

2023-01-25 19:54 UTC, PettitWesley commented on stable/aws-for-fluent-bit/templates/psp.yaml
> +{{- if .Values.rbac.pspEnabled }}
I see so the intention is to make it default false because k8s has removed pod security policy: https://github.com/aws/eks-charts/issues/810

2023-01-25 19:55 UTC, PettitWesley commented on stable/aws-for-fluent-bit/templates/psp.yaml
> +{{- if .Values.rbac.pspEnabled }}
The chart seems to currently have this which defaults false, shouldn't this be used to gate creating this file or not?? https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/values.yaml#L35

2023-01-25 19:56 UTC, PettitWesley commented on stable/aws-for-fluent-bit/templates/psp.yaml
> +{{- if .Values.rbac.pspEnabled }}
Sorry I'm really a novice at some of the things, I need you to explain it to me.

2023-02-01 13:56 UTC, razorsk8jz commented
Looking for updates if changes needed.

2023-02-02 00:56 UTC, PettitWesley requested changes
@razorsk8jz I think you need to update the README with the new option before this can be merged: https://github.com/aws/eks-charts/blob/master/stable/aws-for-fluent-bit/README.md

2023-02-06 17:06 UTC, razorsk8jz commented
Readme Updated

2023-02-16 01:36 UTC, PettitWesley commented on stable/aws-for-fluent-bit/templates/psp.yaml
> +{{- if .Values.rbac.pspEnabled }}
I understand now, this makes it disabled by default, which we want since its deprecated.

2023-02-16 01:40 UTC, PettitWesley approved these changes
Tested, and it works, thanks!

```
helm template --dry-run . --set rbac.pspEnabled="true"
```

2023-02-16 01:42 UTC, merged